name: Janus Docker Image CI

on:
  push:
    branches: [ develop, master ] # Change to 'develop' or another branch if needed
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and test Docker image
        run: |
          docker build -t janus-test:latest .
          docker run --rm -d -p 8088:8088 -p 8188:8188 --name janus-test janus-test:latest
          sleep 5
          docker logs janus-test
          docker stop janus-test

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/janus-gateway:${{ github.sha }}
            docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/janus-gateway:latest
